/**
 * This file was generated by the Jeddict
 */
package com.udea.concesionarioudea.entity.com.udea.concesionarioudea.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Juan Sebastian
 */
@Entity(name = "marca")
public class Marca {

    @Column(name = "id", unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "marca", unique = true, updatable = false, nullable = false)
    @Basic
    private String marca;

    @OneToMany(mappedBy = "marca1")
    private List<Vehiculo> vehiculoes;

    public Marca(Long id, String marca) {
        this.id = id;
        this.marca = marca;
    }

    public Marca() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public List<Vehiculo> getVehiculoes() {
        if (vehiculoes == null) {
            vehiculoes = new ArrayList<>();
        }
        return this.vehiculoes;
    }

    public void setVehiculoes(List<Vehiculo> vehiculoes) {
        this.vehiculoes = vehiculoes;
    }

    public void addVehiculo(Vehiculo vehiculo) {
        getVehiculoes().add(vehiculo);
        vehiculo.setMarca1(this);
    }

    public void removeVehiculo(Vehiculo vehiculo) {
        getVehiculoes().remove(vehiculo);
        vehiculo.setMarca1(null);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Marca other = (Marca) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public String toString() {
        return "Marca{" + " id=" + id + ", marca=" + marca + '}';
    }

}