/**
 * This file was generated by the Jeddict
 */
package com.udea.concesionariofsi.entity.com.udea.concesionariofsi.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

/**
 * @author sirro
 */
@Entity
public class Marca {

    @Column(name = "id", unique = true, updatable = false, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @Column(name = "marca", unique = true, updatable = false, nullable = false, length = 30)
    @Basic
    @NotNull(message = "Debe insertar el nombre de la marca")
    private String marca;

    @OneToMany(mappedBy = "marca")
    private List<Vehiculo> vehiculoes;

    public Marca(int id, String marca, List<Vehiculo> vehiculoes) {
        this.id = id;
        this.marca = marca;
        this.vehiculoes = vehiculoes;
    }

    public Marca() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public List<Vehiculo> getVehiculoes() {
        if (vehiculoes == null) {
            vehiculoes = new ArrayList<>();
        }
        return this.vehiculoes;
    }

    public void setVehiculoes(List<Vehiculo> vehiculoes) {
        this.vehiculoes = vehiculoes;
    }

    public void addVehiculo(Vehiculo vehiculo) {
        getVehiculoes().add(vehiculo);
        vehiculo.setMarca(this);
    }

    public void removeVehiculo(Vehiculo vehiculo) {
        getVehiculoes().remove(vehiculo);
        vehiculo.setMarca(null);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Marca other = (Marca) obj;
        if (this.getId() != other.getId()) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + this.getId();
        return hash;
    }

    @Override
    public String toString() {
        return "Marca{" + " id=" + id + ", marca=" + marca + ", vehiculoes=" + vehiculoes + '}';
    }

}