/**
 * This file was generated by the Jeddict
 */
package com.udea.concesionariofsi.entity.com.udea.concesionariofsi.entity;

import java.util.Date;
import java.util.Objects;
import java.util.Optional;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

/**
 * @author sirro
 */
@Entity(name = "Vehiculo")
@IdClass(VehiculoPK.class)
public class Vehiculo {

    @Column(name = "id", unique = true, updatable = false, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @Column(name = "model", updatable = false, nullable = false)
    @Basic
    private String model;

    @Column(name = "price", nullable = false)
    @Basic
    private double price;

    @Column(name = "pictureUrl", unique = true, nullable = false)
    @Basic
    private String pictureUrl;

    @Column(name = "mileage", nullable = false)
    @Basic
    private double mileage;

    @Column(name = "entryDate", updatable = false, nullable = false)
    @Basic
    @Temporal(TemporalType.DATE)
    private Date entryDate;

    @Column(name = "licensePlate", unique = true)
    @Basic
    private String licensePlate;

    @Column(name = "manufactureYear", updatable = false, nullable = false)
    @Basic
    @Min(value = 4)
    @Max(value = 4)
    private int manufactureYear;

    @Id
    @ManyToOne
    private Marca marca;

    public Vehiculo(int id, String model, double price, String pictureUrl, double mileage, Date entryDate, String licensePlate, int manufactureYear, Marca marca) {
        this.id = id;
        this.model = model;
        this.price = price;
        this.pictureUrl = pictureUrl;
        this.mileage = mileage;
        this.entryDate = entryDate;
        this.licensePlate = licensePlate;
        this.manufactureYear = manufactureYear;
        this.marca = marca;
    }

    public Vehiculo() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getPictureUrl() {
        return this.pictureUrl;
    }

    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    public double getMileage() {
        return this.mileage;
    }

    public void setMileage(double mileage) {
        this.mileage = mileage;
    }

    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public Optional<String> getLicensePlate() {
        return Optional.ofNullable(this.licensePlate);
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    public int getManufactureYear() {
        return this.manufactureYear;
    }

    public void setManufactureYear(int manufactureYear) {
        this.manufactureYear = manufactureYear;
    }

    public Marca getMarca() {
        return this.marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Vehiculo other = (Vehiculo) obj;
        if (this.getId() != other.getId()) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + this.getId();
        return hash;
    }

    @Override
    public String toString() {
        return "Vehiculo{" + " id=" + id + ", model=" + model + ", price=" + price + ", pictureUrl=" + pictureUrl + ", mileage=" + mileage + ", entryDate=" + entryDate + ", licensePlate=" + licensePlate + ", manufactureYear=" + manufactureYear + ", marca=" + marca + '}';
    }

}