//
// This file was generated by the Jeddict
//
package com.udea.concesionariofsi.entity.com.udea.concesionariofsi.entity;

import java.io.Serializable;
import java.util.Objects;

public class VehiculoPK implements Serializable {

    private int id;

    private int marca;

    public VehiculoPK() {
    }

    public VehiculoPK(int id, int marca) {
        this.id = id;
        this.marca = marca;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMarca() {
        return this.marca;
    }

    public void setMarca(int marca) {
        this.marca = marca;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final VehiculoPK other = (VehiculoPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getMarca(), other.getMarca())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + this.getId();
        hash = 31 * hash + Objects.hashCode(this.getMarca());
        return hash;
    }

    @Override
    public String toString() {
        return "VehiculoPK{" + " id=" + id + ", marca=" + marca + '}';
    }

}